# Generated by Django 4.2.6 on 2023-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper_agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
